### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.AsynchronousOperationException
  id: AsynchronousOperationException
  children:
  - System.IdentityModel.AsynchronousOperationException.#ctor
  - System.IdentityModel.AsynchronousOperationException.#ctor(System.Exception)
  - System.IdentityModel.AsynchronousOperationException.#ctor(System.String)
  - System.IdentityModel.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.IdentityModel.AsynchronousOperationException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: AsynchronousOperationException
  nameWithType: AsynchronousOperationException
  fullName: System.IdentityModel.AsynchronousOperationException
  type: Class
  summary: "Wyjątek zgłaszany, gdy wystąpi błąd podczas operacji asynchronicznej."
  syntax:
    content: 'public class AsynchronousOperationException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.IdentityModel.AsynchronousOperationException.#ctor
  id: '#ctor'
  parent: System.IdentityModel.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException()
  nameWithType: AsynchronousOperationException.AsynchronousOperationException()
  fullName: System.IdentityModel.AsynchronousOperationException.AsynchronousOperationException()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.IdentityModel.AsynchronousOperationException&quot;> </xref> klasy."
  remarks: "Ten konstruktor inicjuje <xref:System.Exception.Message%2A>Właściwość nowego wystąpienia systemu dostarczanego przez komunikatu opisującego błąd.</xref:System.Exception.Message%2A> Ten komunikat bierze pod uwagę bieżące ustawienia kulturowe systemu.       W poniższej tabeli przedstawiono początkowe wartości właściwości dla nowego wystąpienia.      | Właściwość | Wartość |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Ciąg z komunikatem o zlokalizowane. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public AsynchronousOperationException ();
    parameters: []
  overload: System.IdentityModel.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.AsynchronousOperationException.#ctor(System.Exception)
  id: '#ctor(System.Exception)'
  parent: System.IdentityModel.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(Exception)
  fullName: System.IdentityModel.AsynchronousOperationException.AsynchronousOperationException(Exception)
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.IdentityModel.AsynchronousOperationException&quot;> </xref> z komunikat dostarczany przez system i odwołanie do wyjątek wewnętrzny będący przyczyną tego wyjątku."
  remarks: "Wyjątek zgłaszany bezpośrednio w wyniku poprzedniego wyjątku powinien zawierać odwołanie do poprzedniego wyjątku we <xref:System.Exception.InnerException%2A>Właściwości.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>Właściwość zwraca tę samą wartość, która została przekazana do konstruktora.</xref:System.Exception.InnerException%2A>       W poniższej tabeli przedstawiono początkowe wartości właściwości dla nowego wystąpienia.      | Właściwość | Wartość |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Wyjątek wewnętrzny odwołania. |   | <xref:System.Exception.Message%2A>| Komunikat dostarczany przez system, który opisuje błąd.</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> Tego komunikatu brane pod uwagę bieżące ustawienia kulturowe systemu. |"
  syntax:
    content: public AsynchronousOperationException (Exception innerException);
    parameters:
    - id: innerException
      type: System.Exception
      description: "<xref:System.Exception>Będący przyczyną bieżącego wyjątku.</xref:System.Exception> Jeśli `innerException` parametr nie jest <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, bieżący wyjątek jest zgłaszany w <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> bloku, który obsługuje wyjątek wewnętrzny."
  overload: System.IdentityModel.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.AsynchronousOperationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.IdentityModel.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(String)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String)
  fullName: System.IdentityModel.AsynchronousOperationException.AsynchronousOperationException(String)
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.IdentityModel.AsynchronousOperationException&quot;> </xref> klasy z powodu określonego błędu."
  remarks: "Ten konstruktor inicjuje <xref:System.Exception.Message%2A>Właściwość nowego przy użyciu wyjątek `message` parametru.</xref:System.Exception.Message%2A> Zawartość `message` ma na celu rozumiane przez człowieka. Element wywołujący tego konstruktora jest wymagana, aby upewnić się, że ten ciąg został zlokalizowany dla bieżącego ustawienia kulturowego systemu.       W poniższej tabeli przedstawiono początkowe wartości właściwości dla nowego wystąpienia.      | Właściwość | Wartość |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Ciąg z komunikatem o. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public AsynchronousOperationException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Komunikat o błędzie opisujący przyczynę wyjątek."
  overload: System.IdentityModel.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.IdentityModel.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(SerializationInfo,StreamingContext)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
  fullName: System.IdentityModel.AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.IdentityModel.AsynchronousOperationException&quot;> </xref> z zserializowanymi danymi."
  remarks: "Ten konstruktor jest wywoływana podczas deserializacji do odtworzenia obiekt wyjątku przesyłane przez strumień."
  syntax:
    content: protected AsynchronousOperationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "A <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> obiekt przechowujący dane serializacji obiektu."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A <xref:System.Runtime.Serialization.StreamingContext>obiekt zawierający informacje kontekstowe dotyczące źródła lub miejsca docelowego.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.IdentityModel.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.AsynchronousOperationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.IdentityModel.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(String,Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String,Exception)
  fullName: System.IdentityModel.AsynchronousOperationException.AsynchronousOperationException(String,Exception)
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.IdentityModel.AsynchronousOperationException&quot;> </xref> z określonego komunikatu o błędzie i odwołania do wyjątek wewnętrzny będący przyczyną tego wyjątku."
  remarks: "Wyjątek zgłaszany bezpośrednio w wyniku poprzedniego wyjątku powinien zawierać odwołanie do poprzedniego wyjątku we <xref:System.Exception.InnerException%2A>Właściwości.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>Właściwość zwraca tę samą wartość, która została przekazana do konstruktora.</xref:System.Exception.InnerException%2A>       W poniższej tabeli przedstawiono początkowe wartości właściwości dla nowego wystąpienia.      | Właściwość | Wartość |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Wyjątek wewnętrzny odwołania. |   | <xref:System.Exception.Message%2A>| Ciąg z komunikatem o. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public AsynchronousOperationException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Komunikat o błędzie opisujący przyczynę wyjątek."
    - id: innerException
      type: System.Exception
      description: "<xref:System.Exception>Będący przyczyną bieżącego wyjątku.</xref:System.Exception> Jeśli `innerException` parametr nie jest <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, bieżący wyjątek jest zgłaszany w <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> bloku, który obsługuje wyjątek wewnętrzny."
  overload: System.IdentityModel.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.IdentityModel.AsynchronousOperationException.#ctor
  parent: System.IdentityModel.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException()
  nameWithType: AsynchronousOperationException.AsynchronousOperationException()
  fullName: System.IdentityModel.AsynchronousOperationException.AsynchronousOperationException()
- uid: System.IdentityModel.AsynchronousOperationException.#ctor(System.Exception)
  parent: System.IdentityModel.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(Exception)
  fullName: System.IdentityModel.AsynchronousOperationException.AsynchronousOperationException(Exception)
- uid: System.IdentityModel.AsynchronousOperationException.#ctor(System.String)
  parent: System.IdentityModel.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(String)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String)
  fullName: System.IdentityModel.AsynchronousOperationException.AsynchronousOperationException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.IdentityModel.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(SerializationInfo,StreamingContext)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
  fullName: System.IdentityModel.AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.IdentityModel.AsynchronousOperationException.#ctor(System.String,System.Exception)
  parent: System.IdentityModel.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(String,Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String,Exception)
  fullName: System.IdentityModel.AsynchronousOperationException.AsynchronousOperationException(String,Exception)
- uid: System.IdentityModel.AsynchronousOperationException.#ctor*
  parent: System.IdentityModel.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException
  nameWithType: AsynchronousOperationException.AsynchronousOperationException
